### ISSUE TITLE
Not compatible with modded paintings (1.21.4)

### ISSUE THREAD

**Issue by ElTryken** [pnk2u/More-Frame-Variants#1]
When I try to use the Macaw paints it has no texture.
![2024-12-15_15 56 47](https://github.com/user-attachments/assets/a7d9a649-c346-45bb-9886-b6a608d0e5a4)

**Comment by pnk2u** [comment]
Thanks for reporting this issue. Should render normally in version 1.1.1.

**Comment by ElTryken** [comment]
> Thanks for reporting this issue. Should render normally in version 1.1.1.

No problem, thx for the quick fix!
